EVENT_RECEIVED = "RECEIVED"
EVENT_PROCESSING = "PROCESSING"
EVENT_COMPLETED = "COMPLETED"
EVENT_FAILED = "FAILED"

STEP_PENDING = "PENDING"
STEP_RUNNING = "RUNNING"
STEP_SUCCESS = "SUCCESS"
STEP_FAILED = "FAILED"

REDIS_EVENT_QUEUE = "REDIS_EVENT_QUEUE"
REDIS_RETRY_QUEUE = "REDIS_RETRY_QUEUE"
REDIS_DLQ = "REDIS_DLQ"
