"""add workflow execution tables

Revision ID: 0b704bd8432a
Revises: a76cbd0a4bff
Create Date: 2026-05-11 12:00:43.007891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b704bd8432a'
down_revision: Union[str, Sequence[str], None] = 'a76cbd0a4bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_event_id'), 'workflow_executions', ['event_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('depends_on_step_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_id'), 'execution_steps', ['id'], unique=False)
    op.create_index(op.f('ix_execution_steps_status'), 'execution_steps', ['status'], unique=False)
    op.create_index(op.f('ix_execution_steps_step_name'), 'execution_steps', ['step_name'], unique=False)
    op.create_index(op.f('ix_execution_steps_workflow_execution_id'), 'execution_steps', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_steps_workflow_execution_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_step_name'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_status'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_event_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
