"""add event fields to workflow executions

Revision ID: 51c6b0924677
Revises: 0b704bd8432a
Create Date: 2026-05-12 12:00:29.181044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c6b0924677'
down_revision: Union[str, Sequence[str], None] = '0b704bd8432a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_steps', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_steps', 'workflow_execution_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('execution_steps', 'input_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_steps', 'output_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_steps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_execution_steps_step_name'), table_name='execution_steps')
    op.drop_constraint(op.f('execution_steps_depends_on_step_id_fkey'), 'execution_steps', type_='foreignkey')
    op.drop_column('execution_steps', 'retry_count')
    op.drop_column('execution_steps', 'depends_on_step_id')
    op.add_column('workflow_executions', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('workflow_executions', sa.Column('entity_id', sa.String(length=100), nullable=True))
    op.add_column('workflow_executions', sa.Column('attempts', sa.Integer(), nullable=False))
    op.alter_column('workflow_executions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('workflow_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workflow_executions', 'retry_count')
    op.drop_column('workflow_executions', 'current_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('current_step', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workflow_executions', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('workflow_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('workflow_executions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('workflow_executions', 'attempts')
    op.drop_column('workflow_executions', 'entity_id')
    op.drop_column('workflow_executions', 'event_type')
    op.add_column('execution_steps', sa.Column('depends_on_step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('execution_steps', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('execution_steps_depends_on_step_id_fkey'), 'execution_steps', 'execution_steps', ['depends_on_step_id'], ['id'])
    op.create_index(op.f('ix_execution_steps_step_name'), 'execution_steps', ['step_name'], unique=False)
    op.alter_column('execution_steps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_steps', 'output_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_steps', 'input_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_steps', 'workflow_execution_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('execution_steps', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
