"""dag_runtime_refactor

Revision ID: 75ae381bf6a6
Revises: 93c583a1d67b
Create Date: 2026-05-26 17:13:00.977310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ae381bf6a6'
down_revision: Union[str, Sequence[str], None] = '93c583a1d67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_steps', sa.Column('step_id', sa.String(), nullable=False))
    op.add_column('execution_steps', sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('execution_steps', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_steps', 'attempts')
    op.drop_column('execution_steps', 'depends_on')
    op.drop_column('execution_steps', 'step_id')
    # ### end Alembic commands ###
