"""refactor workflow execution architecture

Revision ID: b593f84e36d6
Revises: 75ae381bf6a6
Create Date: 2026-05-28 11:58:27.543967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b593f84e36d6'
down_revision: Union[str, Sequence[str], None] = '75ae381bf6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.add_column('workflow_executions', sa.Column('workflow_run_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_workflow_executions_event_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_workflow_run_id'), 'workflow_executions', ['workflow_run_id'], unique=False)
    op.create_foreign_key(None, 'workflow_executions', 'workflow_runs', ['workflow_run_id'], ['id'])
    op.drop_column('workflow_executions', 'event_type')
    op.drop_column('workflow_executions', 'entity_id')
    op.drop_column('workflow_executions', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('workflow_executions', sa.Column('entity_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('workflow_executions', sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_executions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_executions_workflow_run_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_event_id'), 'workflow_executions', ['event_id'], unique=False)
    op.drop_column('workflow_executions', 'workflow_run_id')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###
