"""remove event processing columns

Revision ID: ce198fd74046
Revises: 51c6b0924677
Create Date: 2026-05-12 14:29:49.219667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce198fd74046'
down_revision: Union[str, Sequence[str], None] = '51c6b0924677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_processing', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('event_processing', sa.Column('entity_type', sa.String(length=100), nullable=False))
    op.add_column('event_processing', sa.Column('entity_id', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_event_processing_workflow_id'), table_name='event_processing')
    op.create_index(op.f('ix_event_processing_entity_id'), 'event_processing', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_processing_entity_type'), 'event_processing', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_processing_event_type'), 'event_processing', ['event_type'], unique=False)
    op.drop_column('event_processing', 'last_error')
    op.drop_column('event_processing', 'workflow_id')
    op.drop_column('event_processing', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_processing', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('event_processing', sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_processing', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_event_processing_event_type'), table_name='event_processing')
    op.drop_index(op.f('ix_event_processing_entity_type'), table_name='event_processing')
    op.drop_index(op.f('ix_event_processing_entity_id'), table_name='event_processing')
    op.create_index(op.f('ix_event_processing_workflow_id'), 'event_processing', ['workflow_id'], unique=False)
    op.drop_column('event_processing', 'entity_id')
    op.drop_column('event_processing', 'entity_type')
    op.drop_column('event_processing', 'event_type')
    # ### end Alembic commands ###
