# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"h\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x11\n\tis_edited\x18\x05 \x01(\x08\x12\x12\n\nis_deleted\x18\x06 \x01(\x08\"\x89\x01\n\tChatEvent\x12$\n\x07message\x18\x01 \x01(\x0b\x32\x11.chat.ChatMessageH\x00\x12!\n\x04\x65\x64it\x18\x02 \x01(\x0b\x32\x11.chat.EditRequestH\x00\x12%\n\x06\x64\x65lete\x18\x03 \x01(\x0b\x32\x13.chat.DeleteRequestH\x00\x42\x0c\n\nevent_type\"6\n\x0b\x45\x64itRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x13\n\x0bnew_message\x18\x02 \x01(\t\"#\n\rDeleteRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t2A\n\x0b\x43hatService\x12\x32\n\nChatStream\x12\x0f.chat.ChatEvent\x1a\x0f.chat.ChatEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=124
  _globals['_CHATEVENT']._serialized_start=127
  _globals['_CHATEVENT']._serialized_end=264
  _globals['_EDITREQUEST']._serialized_start=266
  _globals['_EDITREQUEST']._serialized_end=320
  _globals['_DELETEREQUEST']._serialized_start=322
  _globals['_DELETEREQUEST']._serialized_end=357
  _globals['_CHATSERVICE']._serialized_start=359
  _globals['_CHATSERVICE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
